call plug#begin()

Plug 'Valloric/YouCompleteMe', {'do': './install.py --tern-completer'}
Plug 'ap/vim-buftabline'
Plug 'ap/vim-css-color', {'for': ['css', 'scss']}
Plug 'christoomey/vim-tmux-navigator'
Plug 'ciaranm/securemodelines'
Plug 'file-line'
Plug 'freitass/todo.txt-vim'
Plug 'gmarik/sudo-gui.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'ludovicchabant/vim-gutentags'
Plug 'scrooloose/syntastic'
Plug 'sheerun/vim-polyglot'
Plug 'sjl/vitality.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-git'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline'
Plug 'xero/sourcerer.vim'
Plug 'reedes/vim-colors-pencil'

call plug#end()

set t_Co=256
colorscheme sourcerer
set bg=dark
let g:airline_theme='pencil'
let g:airline_left_sep=''
let g:airline_right_sep=''
if !exists('g:airline_symbols')
  let g:airline_symbols={}
endif
let g:airline_symbols.branch='⎇'
let g:airline_symbols.readonly='🔒'

" these plugins are bundled in $VIMRUNTIME
runtime macros/matchit.vim

" basic editor config
syntax on
filetype plugin indent on
set hidden number relativenumber
set expandtab tabstop=2 shiftwidth=2
set autoindent smartindent
set autoread
set incsearch hlsearch showmatch
set ignorecase smartcase
set wildmode=list:longest
set scrolloff=2
set backspace=indent,eol,start whichwrap+=<,>,[,]
set nobackup noswapfile
set encoding=utf-8
set mouse=a
set mousemodel=popup_setpos
set display+=lastline
set shortmess=atI
set laststatus=2
set clipboard=unnamed

" Use cursorline to highlight insert mode
highlight clear CursorLine
autocmd InsertEnter * set cursorline
autocmd InsertLeave * set cursorline!

" ctags
set tags=./tags;,tags;

" vitality
let g:vitality_always_assume_iterm = 1

" quickly edit/reload the vimrc file
nmap <silent> <leader>ev :edit $MYVIMRC<CR>
augroup sourcevimrc " {
  autocmd!
  autocmd BufWritePost $MYVIMRC nested source $MYVIMRC
augroup end " }

" clear search highlight
nmap <leader>/ :noh<CR><ESC>

" better search highlight
" highlight Search ctermbg=blue

" save when focus lost
au FocusLost * silent! w
au FocusLost * silent! stopinsert

" The following two options interfere with one another.
"
" To display tabs and trailing space use :set list
" for word wrapping use :set nolist
nmap <silent> <leader>w :set list!<cr>

" word wrapping
set lbr formatoptions=l

" highlight whitespace
set list listchars=tab:⇥\ ,trail:·
hi Specialkey ctermfg=236 ctermbg=None

" <leader>s:
" toggle syntastic in codeish file
nmap <silent> <leader>s :SyntasticToggle<cr>
" spellcheck in textish files
autocmd FileType txt,markdown,todo nmap <silent> <leader>s :setlocal invspell<CR>

" useful for browsing URLs, opening files in their default app etc
" relies on OS X CLI open command
nmap <silent> go :call system("open " . expand('<cWORD>'))<CR>
vmap <silent> go :call system("open " . @*)<CR>

" drupal stuff
autocmd BufRead,BufNewFile *.module   set filetype=php
autocmd BufRead,BufNewFile *.install  set filetype=php
autocmd BufRead,BufNewFile *.info     set filetype=dosini

" good enough folding for bracey languages
autocmd FileType css,less,javascript setlocal foldmethod=marker
autocmd FileType css,less,javascript setlocal foldmarker={,}
autocmd FileType css,less,javascript normal zR

" nice folding
autocmd BufRead,BufNewFile,BufEnter * hi Folded ctermfg=242 ctermbg=236
set fillchars="fold: "
set foldtext=MyFoldText()
function! MyFoldText()
  let line = getline(v:foldstart)
  if match(line, "/\*\\*") == -1
    " not a docblock
    return line . " …"
  else
    " docblock - is it @file?
    let firstLine = getline(v:foldstart + 1)
    let secondLine = getline(v:foldstart + 2)
    let description = (match(firstLine, "@file") == -1) ? firstLine : secondLine
    return line . substitute(description, "^\\s*\\*", "", "") . " */"
  end
endfunction

" make space toggle folds in
noremap <SPACE> zc
noremap <RETURN> zo

" uh
autocmd BufNewFile,BufRead Gemfile set ft=ruby

" fzf
map <silent> <C-p> :FZF<cr>
map <silent> <C-t> :Tags<cr>
map <silent> <C-r> :BTags<cr>
map <silent> <C-f> :Ag<cr>
map <silent> <C-b> :Buffers<cr>

" limelight
let g:limelight_conceal_ctermfg=240

" syntax folding for php
autocmd FileType php setlocal foldmethod=syntax
autocmd FileType php setlocal foldlevel=99
let php_folding=2
let php_phpdoc_folding=1
nnoremap <leader>f :set foldlevel=0<cr>

" highlight php docblocks
function! PhpSyntaxOverride()
  hi! def link phpDocTags phpDefine
  hi! def link phpDocParam phpType
endfunction

augroup phpSyntaxOverride
  autocmd!
  autocmd FileType php call PhpSyntaxOverride()
augroup END

" syntastic
let g:syntastic_javascript_checkers = ['standard']

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" buftabline
let g:buftabline_show = 1
let g:buftabline_numbers = 1
let g:buftabline_indicators = 1
let g:buftabline_separators = 1
hi! link BufTabLineFill SignColumn
hi! link BufTabLineHidden SignColumn
hi! link BufTabLineActive SignColumn
hi! link BufTabLineCurrent ModeMsg

" auto-pairs
" Interferes with markdown checkboxes.
let g:AutoPairsMapSpace = 0

" Perhaps this will make Vim usable for large PHP files with lots of syntastic
" warnings again?
let g:ycm_register_as_syntastic_checker = 0

" Split shell
nnoremap <c-z> :silent !tmux split-window<cr>
